version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s %(name)-16s %(levelname)-8s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

loggers:
  uvicorn:
    error:
      propagate: true
      level: INFO
  FeslApiClient:
    level: INFO
  TheaterApiClient:
    level: INFO
  pybfbc2stats:
    level: INFO

root:
  level: DEBUG
  handlers: [console]
  propagate: no
