import os

# redis config values
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))
REDIS_PASS = os.getenv('REDIS_PASS', '')
REDIS_KEY_PREFIX = os.getenv('REDIS_KEY_PREFIX', '')

MULTI_LOOKUP_MAX_PERSONAS = os.getenv('MULTI_LOOKUP_MAX_PERSONAS', 30)

CLIENT_USERNAME = os.getenv('CLIENT_USERNAME')
CLIENT_PASSWORD = os.getenv('CLIENT_PASSWORD')
CLIENT_TIMEOUT = float(os.getenv('CLIENT_TIMEOUT', 3.0))
CLIENT_MAX_RETRIES = int(os.getenv('CLIENT_MAX_RETRIES', 2))
CLIENT_PING_INTERVAL = float(os.getenv('CLIENT_PING_INTERVAL', 150.0))

CACHE_TTL_DEFAULT = os.getenv('CACHE_TTL_DEFAULT', 600)
CACHE_TTL_PERSONA_SEARCH = os.getenv('CACHE_TTL_PERSONA_SEARCH', 1800)
CACHE_TTL_PERSONAS_BY_NAME = os.getenv('CACHE_TTL_PERSONAS_BY_NAME', 28800)
CACHE_TTL_PERSONAS_BY_ID = os.getenv('CACHE_TTL_PERSONAS_BY_ID', 14400)
CACHE_TTL_SERVERS = os.getenv('CACHE_TTL_SERVERS', 60)
CACHE_MAX_AGE_DEFAULT = os.getenv('CACHE_MAX_AGE_DEFAULT', 600)
CACHE_MAX_AGE_PERSONA_SEARCH = os.getenv('CACHE_MAX_AGE_PERSONA_SEARCH', 1800)
CACHE_MAX_AGE_PERSONAS = os.getenv('CACHE_MAX_AGE_PERSONAS', 28800)
CACHE_MAX_AGE_SERVERS = os.getenv('CACHE_MAX_AGE_SERVERS', 60)
